### ISSUE TITLE
Can't add attachement

### ISSUE THREAD

**Issue by nnm-afaya** [nvt-ak/quill-upload#51]
index.js:13 Uncaught ReferenceError: href is not defined
    at AttachmentBlot.create (index.js:13:7)
    at Object.create (quill.js:183:87)
    at BlockBlot2.insertAt (quill.js:7483:33)
    at Block2.insertAt (quill.js:905:123)
    at ContainerBlot2.insertAt (quill.js:3454:19)
    at ScrollBlot2.insertAt (quill.js:7218:35)
    at Scroll2.insertAt (quill.js:4324:103)
    at Editor2.insertEmbed (quill.js:2656:19)
    at quill.js:1429:30
    at Quill2.modify (quill.js:1660:16)

![image](https://github.com/nvt-ak/quill-upload/assets/112549951/fb1c50cc-7fab-4754-ba8f-5b2665f35a3e)

**Comment by Anderson-Portes** [comment]
i have the same problem

**Comment by Anderson-Portes** [comment]
![image](https://github.com/nvt-ak/quill-upload/assets/96482967/46d53283-c5a5-4eef-b53a-0d6d350c5070)

i need to declare the href variable, and works fine!

**Comment by nvt-ak** [comment]
@Anderson-Portes Thank you, I fixed on latest version!
